import type { VehicleBrand } from "@/types/vehicle";

// Replace this catalog with a database or external vehicle API without changing the UI contract.
export const vehicleBrands: VehicleBrand[] = [
  // Türkiye'de aktif satılan / ikinci el pazarında yaygın markalar
  ["Alfa Romeo", "Giulietta,Junior,Tonale,Giulia,Stelvio"],
  ["Audi", "A1,A3,A4,A5,A6,A7,A8,Q2,Q3,Q5,Q7,Q8,RS3,RS4,RS5,RS6,RS7,S3,S4,S5,S6,S7,S8,SQ5,SQ7,SQ8"],
  ["BMW", "1 Serisi,2 Serisi,3 Serisi,4 Serisi,5 Serisi,6 Serisi,7 Serisi,X1,X2,X3,X4,X5,X6,M2,M3,M4,M5,M8"],
  ["Chery", "Tiggo 7 Pro,Tiggo 8 Pro,Omoda 5"],
  ["Citroen", "C3,C4,C5 Aircross,Berlingo"],
  ["Cupra", "Formentor,Born,Ateca,Leon,Terramar"],
  ["Dacia", "Sandero,Duster,Jogger,Spring"],
  ["Fiat", "Egea,Egea Cross,Egea Hatchback,500,500X,500L,Panda,Tipo,Doblo,Fiorino"],
  ["Ford", "Fiesta,Focus,Puma,Kuga,Transit,Tourneo,Mustang,Ranger"],
  ["Honda", "Civic,City,CR-V,HR-V"],
  ["Hyundai", "i10,i20,i30,Bayon,Kona,Tucson,Elantra,Santa Fe"],
  ["Jeep", "Renegade,Compass,Avenger,Wrangler,Grand Cherokee"],
  ["Kia", "Picanto,Rio,Ceed,Sportage,Stonic,EV3,EV6,EV9,Niro,XCeed,Sorento"],
  ["Land Rover", "Defender,Discovery,Discovery Sport,Range Rover,Range Rover Sport,Range Rover Velar,Range Rover Evoque"],
  ["Mazda", "Mazda 2,Mazda 3,CX-3,CX-5,MX-5"],
  ["Mercedes-Benz", "A-Serisi,B-Serisi,C-Serisi,E-Serisi,S-Serisi,CLA,GLA,GLB,GLC,GLE,GLS,AMG GT,EQA,EQB,EQE,EQS,G Serisi"],
  ["MG", "MG3,MG4,ZS,HS,Marvel R"],
  ["Mini", "Cooper,Countryman,Clubman"],
  ["Mitsubishi", "ASX,L200,Eclipse Cross,Space Star"],
  ["Nissan", "Micra,Juke,Qashqai,X-Trail"],
  ["Opel", "Corsa,Astra,Mokka,Crossland,Grandland,Insignia,Frontera"],
  ["Peugeot", "208,308,408,2008,3008,5008"],
  ["Renault", "Clio,Megane,Taliant,Captur,Austral,Duster,Spring,Fluence,Kadjar,Kangoo"],
  ["Seat", "Ibiza,Leon,Arona,Ateca,Tarraco"],
  ["Skoda", "Fabia,Scala,Octavia,Kamiq,Karoq,Kodiaq,Superb,Enyaq"],
  ["Suzuki", "Swift,Vitara,S-Cross,Jimny"],
  ["Togg", "T10X,T10F"],
  ["Toyota", "Yaris,Corolla,C-HR,Hilux,RAV4,Camry,Yaris Cross,Corolla Cross,Prius,Land Cruiser"],
  ["Volkswagen", "Polo,Golf,Taigo,T-Roc,Tiguan,Passat,Arteon,Touareg,T-Cross,Jetta,Transporter,Caddy,ID.3,ID.4,ID.5,ID.7"],
  ["Volvo", "S60,S90,XC40,XC60,XC90,EX30,EX40,EX90"],
  // Küresel çaptaki diğer markalar
  ["Abarth", "500,595,695"],
  ["Acura", "ILX,MDX,RDX,TLX"],
  ["Aiways", "U5,U6"],
  ["Alpine", "A110,A290"],
  ["Anadol", "A1,A2,STC-16"],
  ["Aston Martin", "Vantage,DB11,DB12,DBX"],
  ["BAIC", "X35,X55"],
  ["Bentley", "Continental GT,Flying Spur,Bentayga"],
  ["Buick", "Encore,Envision,LaCrosse"],
  ["BYD", "Atto 3,Seal,Dolphin,Han,Tang"],
  ["Cadillac", "CTS,Escalade,XT5"],
  ["Chevrolet", "Aveo,Cruze,Captiva,Trax,Camaro,Silverado"],
  ["Chrysler", "300C,PT Cruiser,Voyager"],
  ["Daewoo", "Lanos,Matiz,Nubira"],
  ["Daihatsu", "Cuore,Sirion,Terios"],
  ["DFSK", "Fengon 5,Fengon 500"],
  ["Dodge", "Challenger,Charger,Durango,Journey,RAM 1500"],
  ["DS Automobiles", "DS 3,DS 4,DS 7,DS 9"],
  ["Ferrari", "Roma,Portofino,296,812,Purosangue"],
  ["Genesis", "G70,G80,G90,GV60,GV70,GV80"],
  ["Geely", "Coolray,Emgrand,Monjaro"],
  ["GMC", "Sierra,Yukon,Canyon,Terrain,Acadia"],
  ["Great Wall", "Haval H6,Haval H9,Poer"],
  ["Hongqi", "E-HS9,H9"],
  ["Hummer", "H2,H3"],
  ["Infiniti", "FX,Q30,Q50,QX70"],
  ["Isuzu", "D-Max,MU-X"],
  ["Jaecoo", "J7,J8"],
  ["Jaguar", "XE,XF,E-Pace,F-Pace,I-Pace"],
  ["KGM", "Torres,Actyon,Tivoli,Korando,Musso,Rexton"],
  ["Lada", "Niva,Samara,Vesta"],
  ["Lamborghini", "Huracan,Urus,Revuelto"],
  ["Lancia", "Delta,Ypsilon,Stratos"],
  ["Leapmotor", "T03,C10"],
  ["Lexus", "UX,NX,RX,ES,LS,LC"],
  ["Lincoln", "Aviator,Continental,Navigator"],
  ["Lotus", "Elise,Emira,Evora,Emeya"],
  ["Lucid", "Air,Gravity"],
  ["Maserati", "Ghibli,Quattroporte,Levante,Grecale,GranTurismo"],
  ["Maxus", "eDeliver 3,eDeliver 9,T60"],
  ["Maybach", "S 580,GLS 600,EQS 680"],
  ["McLaren", "570S,720S,Artura,750S"],
  ["Nio", "ET5,ET7,ES6,ES8,EL6"],
  ["Omoda", "5,9"],
  ["Polestar", "2,3,4"],
  ["Porsche", "Macan,Cayenne,Panamera,911,Taycan,718"],
  ["Proton", "Gen-2,Saga,X50"],
  ["RAM", "1500,2500,ProMaster"],
  ["Rolls-Royce", "Ghost,Phantom,Cullinan,Spectre,Silver Shadow"],
  ["Rover", "25,45,75"],
  ["Saab", "9-3,9-5"],
  ["Seres", "3,5"],
  ["Skywell", "ET5,HT-i"],
  ["Smart", "Fortwo,Forfour,#1,#3"],
  ["SsangYong", "Korando,Musso,Rexton,Tivoli,Torres"],
  ["Subaru", "XV,Forester,Outback,Impreza,Legacy,WRX"],
  ["Tata", "Indica,Indigo,Nexon"],
  ["Tesla", "Model 3,Model Y,Model S,Model X,Cybertruck"],
  ["TOFAŞ", "Doğan,Kartal,Şahin"],
  ["Voyah", "Free,Dream"],
  ["XPeng", "G6,G9,P7"],
  ["Zeekr", "001,X,7X"],
].map(([name, models]) => ({ name, slug: name.toLowerCase().replaceAll(" ", "-"), models: models.split(",").map((model) => model.trim()) })).sort((a, b) => a.name.localeCompare(b.name, "tr-TR"));

export function getPopularModelsForBrand(brand?: string): string[] {
  return vehicleBrands.find((item) => item.name === brand)?.models ?? [];
}

export function getModelsForBrand(brand?: string): string[] {
  const listed = getPopularModelsForBrand(brand);
  return [...new Set([...listed, ...(additionalModels[brand ?? ""] ?? [])])].sort((a, b) => a.localeCompare(b, "tr-TR"));
}

// Historical model names supplied for Turkey's used-car selection. Technical variants
// are kept separately because a model name alone does not prove year/engine/trim fit.
const additionalModels: Record<string, string[]> = {
  "TOFAŞ": ["Murat 124", "Murat 131"],
  "Renault": ["Renault 9", "Renault 11", "Renault 12", "Renault 19", "Broadway", "Fairway", "Flash", "Toros", "Symbol", "Thalia", "Laguna", "Latitude", "Scenic", "Talisman", "Rafale"],
  "Fiat": ["Uno", "Tempra", "Palio", "Siena", "Albea", "Marea", "Brava", "Bravo", "Punto", "Grande Punto", "Egea Station Wagon", "Linea"],
  "Ford": ["Taunus", "Escort", "Fusion", "Mondeo", "B-Max", "C-Max", "S-Max", "Mustang Mach-E", "Courier", "Connect", "Tourneo Connect"],
  "Opel": ["Vectra", "Omega", "Calibra", "Tigra", "Meriva", "Zafira", "Combo"],
  "Volkswagen": ["Bora", "Scirocco", "Beetle", "Eos", "CC", "Tayron", "Caravelle", "Amarok", "Tiguan Allspace", "Passat Variant"],
  "Toyota": ["Starlet", "Auris", "Avensis", "Carina", "Corona"],
  "Honda": ["Accord", "Jazz", "CR-X", "CR-Z", "Integra", "Prelude", "ZR-V"],
  "Hyundai": ["Excel", "Accent Era", "Accent Blue", "Getz", "Atos", "Sonata", "Coupe", "Matrix", "Ioniq", "Ioniq 5", "Ioniq 6"],
  "Kia": ["Pride", "Cerato", "Sephia", "Shuma"],
  "Peugeot": ["106", "205", "206", "207", "301", "306", "307", "405", "406", "407", "508", "4007", "Partner", "Rifter", "E-208", "RCZ"],
  "Citroen": ["Saxo", "Xsara", "C2", "C3 Aircross", "C4 X", "C4 Cactus", "C5", "C-Elysée", "Ami"],
  "Nissan": ["Almera", "Primera", "Sunny", "Note", "Tiida", "Pathfinder", "Navara", "Patrol", "200SX", "350Z", "370Z", "GT-R"],
  "Skoda": ["Favorit", "Felicia", "Roomster", "Rapid", "Elroq"],
  "Seat": ["Cordoba", "Toledo", "Altea"],
  "BMW": ["8 Serisi", "Z3", "Z4", "X7", "i3", "i4", "i5", "i7", "iX1", "iX2", "iX3", "iX"],
  "Mercedes-Benz": ["190", "CLS", "CLK", "SLK", "SLC", "SL", "Vito", "Viano", "V Serisi"],
  "Volvo": ["S40", "S70", "S80", "V40", "V50", "V60", "V70", "V90", "C30", "C70", "XC70"],
  "Dacia": ["Sandero Stepway", "Lodgy", "Dokker", "Bigster", "Logan"],
  "Alfa Romeo": ["Giulia", "Stelvio", "147", "156", "159", "GT", "MiTo", "Spider", "Brera"],
  "Audi": ["TT", "R8", "Q4 e-tron", "Q6 e-tron", "e-tron", "e-tron GT"],
  "Mazda": ["MX-5", "CX-30", "CX-60", "RX-8"],
  "Mitsubishi": ["Colt", "Galant", "Carisma", "Pajero", "Outlander"],
  "Suzuki": ["Baleno", "Ignis", "Alto", "Grand Vitara"],
  "Subaru": ["BRZ", "Levorg"],
  "Land Rover": ["Freelander", "Discovery 4", "Range Rover Sport SVR"],
  "Mini": ["Paceman", "Roadster", "Cabrio"],
};
